services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: reminder-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - time-tracking-network

  mysql:
    image: mysql:8.4
    container_name: reminder-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: electronic-time-marking
      MYSQL_ROOT_HOSTS: "%"
      MYSQL_ALLOW_EMPTY_PASSWORD: "1"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - time-tracking-network

volumes:
  rabbitmq_data:
  mysql_data:

networks:
  time-tracking-network:
    name: time-tracking-network
